from abc import ABC, abstractmethod
from typing import List, Optional, Generic, TypeVar

T = TypeVar("T")

class IRepository(ABC, Generic[T]):
    @abstractmethod
    def add(self, obj: T) -> None: ...
    @abstractmethod
    def get(self, id: str) -> Optional[T]: ...
    @abstractmethod
    def list(self) -> List[T]: ...
    @abstractmethod
    def update(self, obj: T) -> None: ...
    @abstractmethod
    def remove(self, id: str) -> None: ...