from typing import Protocol
from src.finance.domain.entities import BankAccount, Category, Operation

class ExportVisitor(Protocol):
    def visit_account(self, account: BankAccount) -> None: ...
    def visit_category(self, category: Category) -> None: ...
    def visit_operation(self, operation: Operation) -> None: ...
    def result(self) -> str: ...
